### ISSUE TITLE
[BUG] radialmenu stuck ui

### ISSUE THREAD

**Issue by oye-zzzzuuuu** [qbcore-framework/qb-radialmenu#128]
**Describe the bug**
Radial menu stuck sometimes.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 2-3 days before
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
No
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
No

**Comment by kayotimoteo** [comment]
Same problem here.

**Comment by sinphoenix** [comment]
After the latest update, are you still getting this error?

**Comment by sinphoenix** [comment]
i see there was an update recently. Please try to see if that will fix the
issue and let me know. I will dig more if this didnt fix it

**Comment by sinphoenix** [comment]
Is this still an issue?

**Comment by UnboundGodz** [comment]
The UI bug is still occurring. Just by spamming the button it will bug out and stick to screen.

**Comment by Griiimon** [comment]
I had the same bug occur yesterday after i turned on toggle in the config. Because I wasn't used to the toggle behavior at first I pressed f1 and clicked wildly and got it stuck. Pressing f1 again would open a second radial menu on top of the one that was stuck . The latter worked fine but the first one still stuck on screen with no way to get it closed other than restarting.

**Comment by Gokaic** [comment]
I commented out the ability to close the menu on toggle or key up for F1 in main.js, and it fixed the issue.

**Comment by AlphaCarry** [comment]
Is it have any solutions?
